In [2]:
import numpy as np
import torch

data = np.load("embeddings_80.npz", allow_pickle=True)

In [21]:
import numpy as np
import os

# List of npz files
# npz_files = ['models/24b069cf-59c6-40c4-ba49-08b8a6217f14.npz', 
#              'models/2ed2fbc0-28b9-4ad0-bfde-06052a36e6bc.npz', 
#              'models/575435bc-d2fe-4919-8e9c-5a13e93ea106.npz', 
#              'models/5ff805be-9a1e-4c8f-b91a-b5dc80420bcf.npz', 
#              'models/e2fb1457-9fdf-46fa-91d0-9b13f723cb32.npz']

npz_files = [
    'models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz',
    'models/39813543-2407-4fe5-830d-04297b6577f5.npz',
    # 'models/5401c48e-13d1-46c5-a8ef-1c5db36f428e.npz',
    'models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz',
    'models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz',
    'models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz'
]




# Dictionary to hold the data
data = {}

# Load each file
for file in npz_files:
    if os.path.exists(file):
        data[file] = np.load(file, allow_pickle=True)
    else:
        print(f"File {file} does not exist.")

In [22]:
len(data)

5

In [23]:
def load_embeddings(path):
    """
    Load serialized embeddings from a binary object file.

    :param path: Path to the compressed archive file.
    :return: A list of lists, where each inner list contains embeddings for a batch within an epoch.
    """
    # Load the compressed archive
    compressed_archive = np.load(path, allow_pickle=True)

    # Extract the embeddings from the archive
    all_batch_embeddings = []
    for epoch_idx in sorted(compressed_archive.keys()):
        epoch_embeddings = compressed_archive[epoch_idx]
        all_batch_embeddings.append(epoch_embeddings)

    print(f"Embeddings loaded from compressed archive: {path}")
    # logger.info(f"Embeddings loaded from compressed archive: {path}")

    return all_batch_embeddings

In [34]:
npz_files = [
    'models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz',
    'models/39813543-2407-4fe5-830d-04297b6577f5.npz',
    # 'models/5401c48e-13d1-46c5-a8ef-1c5db36f428e.npz',
    'models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz',
    'models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz',
    'models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz'
]

# Iterate through each file
client_embeddings = []
for file in npz_files:
    # Load embeddings using the provided function
    embeddings = load_embeddings(file)
    
    # Print the required information
    print(f"Filename: {file}")
    print(f"Length: {len(embeddings)}")
    client_embeddings.append(embeddings)
    # print(f"First element: {embeddings[0] if embeddings else 'No embeddings'}")

Embeddings loaded from compressed archive: models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz
Filename: models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz
Length: 1
Embeddings loaded from compressed archive: models/39813543-2407-4fe5-830d-04297b6577f5.npz
Filename: models/39813543-2407-4fe5-830d-04297b6577f5.npz
Length: 1
Embeddings loaded from compressed archive: models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz
Filename: models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz
Length: 1
Embeddings loaded from compressed archive: models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz
Filename: models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz
Length: 1
Embeddings loaded from compressed archive: models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz
Filename: models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz
Length: 1


In [36]:
len(client_embeddings)

5

# Prepping embeddings

In [25]:
def merge_client_data(client_data):
    """
    Merge embeddings for each batch within an epoch into a single ndarray.

    :param client_data: A list of lists, where each inner list contains embeddings for a batch within an epoch.
    :return: A list of ndarrays, where each ndarray contains all embeddings for a given epoch.
    """
    # Single client
    # client_data = load_embeddings(file)
    # client_data[0][0].shape -> (256, 7)
    # Merge all batch ndarrays into one ndarray for each epoch
    merged_client_data = [np.vstack(epoch_data) for epoch_data in client_data]
    # Now, when calling merged_client_data[0], it will return an ndarray with size of dataset_size x 7
    # merged_client_data[0].shape -> (23526, 7)

    return merged_client_data


In [20]:
# sample_data[0][0].shape


(256, 7)

In [14]:
# Merge all batch ndarrays into one ndarray for each epoch
# merged_sample_data = [np.vstack(epoch_data) for epoch_data in sample_data]

# Now, when calling merged_sample_data[0], it will return an ndarray with size of dataset_size x 7


In [15]:
# merged_sample_data[0].shape

(23526, 7)

In [26]:
other_clients_data = []
for file in npz_files[1:]:
    # client_data = load_embeddings(file)
    merged_client_data = merge_client_data(file)
    other_clients_data.append(merged_client_data)

Embeddings loaded from compressed archive: models/39813543-2407-4fe5-830d-04297b6577f5.npz
Embeddings loaded from compressed archive: models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz
Embeddings loaded from compressed archive: models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz
Embeddings loaded from compressed archive: models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz


In [27]:
# Assuming `merged_sample_data` contains the data from the current client
# and `other_clients_data` is a list of similar data from other clients

# Example of other_clients_data
# other_clients_data = [client1_data, client2_data, client3_data, client4_data]

# Concatenate the data from all clients vertically
first_client = merge_client_data(npz_files[0])
all_clients_data = [first_client[0]]  # Start with the current client's data
all_clients_data.extend([client_data[0] for client_data in other_clients_data])

# Stack all data vertically
final_data = np.hstack(all_clients_data)

# Print the shape of the final concatenated data
print(final_data.shape)  # Should be (dataset_size, 35)


Embeddings loaded from compressed archive: models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz
(23526, 35)


In [28]:
final_data[0]

array([ 0.      , 29.632975,  0.      , 16.393158, 39.411644, 20.702461,
        0.      ,  0.      , 44.715748,  0.      , 24.86609 , 59.163128,
       30.734125,  0.      ,  0.      , 29.79511 ,  0.      , 16.5286  ,
       39.63214 , 20.545433,  0.      ,  0.      , 29.760174,  0.      ,
       16.47684 , 39.616657, 20.56148 ,  0.      ,  0.      , 44.565174,
        0.      , 24.846571, 58.853867, 30.768682,  0.      ],
      dtype=float32)

In [31]:
import torch
final_data_tensor = torch.from_numpy(final_data)

In [32]:
final_data_tensor.shape

torch.Size([23526, 35])

In [44]:
# also using client_embeddings make a client_embeddings_dict with client id as key and embeddings as value
client_embeddings_dict = {client_id+1: embeddings for client_id, embeddings in enumerate(client_embeddings)}

In [45]:
client_embeddings_dict.keys()

dict_keys([1, 2, 3, 4, 5])

In [61]:
client_embeddings[5][0].shape

IndexError: list index out of range

In [55]:
for client_id, embeddings in client_embeddings_dict.items():
    print("Client ID:", client_id)
    print("Embeddings shape:", embeddings[0].shape)
    print(type(embeddings))

Client ID: 1
Embeddings shape: (92,)
<class 'list'>
Client ID: 2
Embeddings shape: (92,)
<class 'list'>
Client ID: 3
Embeddings shape: (92,)
<class 'list'>
Client ID: 4
Embeddings shape: (92,)
<class 'list'>
Client ID: 5
Embeddings shape: (92,)
<class 'list'>


In [64]:
def load_embeddings(path):
    """
    Load serialized embeddings from a binary object file.

    :param path: Path to the compressed archive file.
    :return: A list of lists, where each inner list contains embeddings for a batch within an epoch.
    """
    # Load the compressed archive
    compressed_archive = np.load(path, allow_pickle=True)

    # Extract the embeddings from the archive
    all_batch_embeddings = []
    for epoch_idx in sorted(compressed_archive.keys()):
        epoch_embeddings = compressed_archive[epoch_idx]
        all_batch_embeddings.append(epoch_embeddings)

    print(f"Embeddings loaded from compressed archive: {path}")
    # logger.info(f"Embeddings loaded from compressed archive: {path}")

    return all_batch_embeddings

npz_files = [
    'models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz',
    'models/39813543-2407-4fe5-830d-04297b6577f5.npz',
    # 'models/5401c48e-13d1-46c5-a8ef-1c5db36f428e.npz',
    'models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz',
    'models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz',
    'models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz'
]

# Iterate through each file
client_embeddings = []
for file in npz_files:
    # Load embeddings using the provided function
    embeddings = load_embeddings(file)
    
    # Print the required information
    print(f"Filename: {file}")
    print(f"Length: {len(embeddings)}")
    client_embeddings.append(embeddings)
    # print(f"First element: {embeddings[0] if embeddings else 'No embeddings'}")

# Using client_embeddings, make a client_embeddings_dict with client id as key and embeddings as value
client_embeddings_dict = {client_id+1: embeddings for client_id, embeddings in enumerate(client_embeddings)}


def merge_client_data(client_data):
    """
    Merge embeddings for each batch within an epoch into a single ndarray.

    :param client_data: A list of lists, where each inner list contains embeddings for a batch within an epoch.
    :return: A list of ndarrays, where each ndarray contains all embeddings for a given epoch.
    """
    # Single client
    # client_data = load_embeddings(file)
    # client_data[0][0].shape -> (256, 7)
    # Merge all batch ndarrays into one ndarray for each epoch
    merged_client_data = [np.vstack(epoch_data) for epoch_data in client_data]
    # Now, when calling merged_client_data[0], it will return an ndarray with size of dataset_size x 7
    # merged_client_data[0].shape -> (23526, 7)

    return merged_client_data

def make_x_input_tensor(client_embeddings_dict):
    # first_client = merge_client_data(client_embeddings[0])
    # all_clients_data = [first_client[0]]  # Start with the first client's data

    # other_clients_data = []
    # for client_data in client_embeddings[1:]:
    #     merged_client_data = merge_client_data(client_data)
    #     other_clients_data.append(merged_client_data)

    all_clients_data = []
    
    for client_id in sorted(client_embeddings_dict.keys()):
        client_data = client_embeddings_dict[client_id]
        merged_client_data = merge_client_data(client_data)
        all_clients_data.append(merged_client_data[0])

    # all_clients_data.extend([client_data[0] for client_data in other_clients_data])

    # Stack all data vertically
    final_data_np = np.hstack(all_clients_data)

    # Convert to torch tensor
    final_data_tensor = torch.from_numpy(final_data_np)
    
    return final_data_tensor, final_data_np

# Example usage:
# final_data_tensor = make_x_input_tensor(npz_files)
x_input, x_input_np = make_x_input_tensor(client_embeddings_dict)
print(x_input.shape)

Embeddings loaded from compressed archive: models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz
Filename: models/1e0f422a-9064-4379-a3bb-d49ef138e31c.npz
Length: 1
Embeddings loaded from compressed archive: models/39813543-2407-4fe5-830d-04297b6577f5.npz
Filename: models/39813543-2407-4fe5-830d-04297b6577f5.npz
Length: 1
Embeddings loaded from compressed archive: models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz
Filename: models/ce5ef1e3-65bb-4e37-8ada-4b6b4f10c75c.npz
Length: 1
Embeddings loaded from compressed archive: models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz
Filename: models/cf213e76-5247-4c59-94ee-38adccdd9c4e.npz
Length: 1
Embeddings loaded from compressed archive: models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz
Filename: models/f88688ca-1e8c-4f39-ae48-92c2bd9ed6f5.npz
Length: 1
torch.Size([23526, 35])


In [68]:
x_input.shape[0]

23526

In [69]:
x_input

tensor([[ 0.0000, 29.6330,  0.0000,  ..., 58.8539, 30.7687,  0.0000],
        [ 0.0000, 29.8508,  0.0000,  ..., 39.3433, 20.7495,  0.0000],
        [ 0.0000, 44.5594,  0.0000,  ...,  0.0000,  0.1856,  0.0000],
        ...,
        [ 0.0000, 44.6442,  0.0000,  ..., 78.6103, 40.9859,  0.0000],
        [ 0.0000, 29.6561,  0.0000,  ..., 78.6103, 40.9859,  0.0000],
        [ 0.0000, 29.8508,  0.0000,  ..., 82.6837, 42.9602,  0.0000]])

In [2]:
import math
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, Subset

In [79]:
labels = torch.load("data/clients/1/labels/IOT_normal_base_labels.pt")
dataset = TensorDataset(x_input, labels)
train_loader = DataLoader(dataset, batch_size=256, shuffle=False)

In [86]:
for batch_x, batch_y in train_loader:
    print('batch_x size:', batch_x.size())
    print('batch_y size:', batch_y.size())
    break

batch_x size: torch.Size([256, 35])
batch_y size: torch.Size([256])


In [3]:
labels = torch.load("data/clients/1/labels/IOT_normal_base_labels.pt")
labels = labels['y_train']

In [77]:
type(labels)

torch.Tensor

In [32]:
np_test = labels['y_train'].numpy()

In [33]:
np_test.shape

(23526,)

In [39]:
labels['y_train'].shape

torch.Size([23526])

In [ ]:
import torch

# Assuming `merged_sample_data` contains the data from the current client
# and `other_clients_data` is a list of similar data from other clients

# placeholder
merged_sample_data = None

# Convert numpy arrays to torch tensors
merged_sample_data_torch = [torch.tensor(epoch_data) for epoch_data in merged_sample_data]
other_clients_data_torch = [[torch.tensor(client_data) for client_data in client] for client in other_clients_data]

# Concatenate the data from all clients vertically
all_clients_data_torch = [merged_sample_data_torch[0]]  # Start with the current client's data
all_clients_data_torch.extend([client_data[0] for client_data in other_clients_data_torch])

# Stack all data vertically
final_data_torch = torch.hstack(all_clients_data_torch)

# Print the shape of the final concatenated data
print(final_data_torch.shape)  # Should be (dataset_size, 35)

# Create a dataset and dataloader
labels = torch.load('/app/data/IOT_normal_base_labels.pt')
dataset = torch.utils.data.TensorDataset(final_data_torch, labels)
dataloader = torch.utils.data.DataLoader(dataset, batch_size=32, shuffle=True)


In [3]:
data = load_embeddings("embeddings_80.npz")

Embeddings loaded from compressed archive: embeddings_80.npz


In [4]:
data

[array([array([[ 0.      , 29.72188 ,  0.      , ..., 39.406696, 20.516958,
                 0.      ],
               [ 0.      , 29.897268,  0.      , ..., 39.635662, 20.267746,
                 0.      ],
               [ 0.      , 29.727663,  0.      , ..., 39.362312, 20.455723,
                 0.      ],
               ...,
               [ 0.      , 29.856546,  0.      , ..., 39.664562, 20.345018,
                 0.      ],
               [ 0.      , 29.80836 ,  0.      , ..., 39.64061 , 20.45325 ,
                 0.      ],
               [ 0.      , 29.692728,  0.      , ..., 39.34683 , 20.471767,
                 0.      ]], dtype=float32)                                ,
        array([[ 0.      , 30.523088,  0.      , ..., 40.48048 , 21.178658,
                 0.      ],
               [ 0.      , 29.638754,  0.      , ..., 39.36726 , 20.64123 ,
                 0.      ],
               [ 0.      , 29.802576,  0.      , ..., 39.684994, 20.514484,
                 0.    

In [5]:
#print shape of data
len(data)

50

In [13]:
for i in range(len(data)):
    print(data[i].shape)
    print(type(data[i]))

(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<class 'numpy.ndarray'>
(92,)
<cla

# Combiner Outputs

In [2]:
import numpy as np
import torch

# Load the files from the folder combiner_out/data
client_gradients = np.load('combiner_out/data/client_gradients.npz', allow_pickle=True)
client_gradients_2 = np.load('combiner_out/data/client_gradients_2.npz', allow_pickle=True)
x_input_with_grads = torch.load('combiner_out/data/x_input_with_grads.pt')

# Print the keys of the loaded files to verify
print(client_gradients.files)
print(client_gradients_2.files)
print(x_input_with_grads.shape)


['1', '2', '3', '4', '5']
['1', '2', '3', '4', '5']
torch.Size([23526, 35])


In [3]:
# get first file from client_gradients
client_gradients_1 = client_gradients['1']
client_gradients_1[0]

array([-1.4266476e-05, -4.1493780e-07,  1.1812810e-05,  7.5877974e-06,
        6.5350819e-06,  1.5283265e-05, -3.6409006e-08], dtype=float32)

In [4]:
x_input_with_grads[0].grad

/tmp/ipykernel_431873/3406955640.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  x_input_with_grads[0].grad
